version: "3"
services:
  openq-oracle:
    container_name: openq-oracle
    build:
      dockerfile: Dockerfile.dev
      context: ./OpenQ-Oracle
    ports:
      - "8090:8090"
    env_file:
      - ./OpenQ-Contracts/.env
      - ./OpenQ-Oracle/.env
      - ./OpenQ-Contracts/.env.contracts
    volumes:
      - /app/node_modules
      - ./OpenQ-Oracle:/app
      - ./OpenQ-Contracts/artifacts:/app/artifacts
  openq-coinapi:
    container_name: openq-coinapi
    build:
      dockerfile: Dockerfile.dev
      context: ./OpenQ-CoinAPI
    ports:
      - "8081:8081"
    volumes:
      - /app/node_modules
      - ./OpenQ-CoinAPI:/app
    env_file:
      - ./OpenQ-CoinAPI/.env
  openq-frontend:
    container_name: openq-frontend
    build:
      dockerfile: Dockerfile.dev
      context: ./OpenQ-Frontend
    ports:
      - "3000:3000"
    env_file:
      - ./OpenQ-Contracts/.env
      - ./OpenQ-Frontend/.env
      - ./OpenQ-Contracts/.env.contracts
    volumes:
      - /app/node_modules
      - ./OpenQ-Frontend:/app
      - ./OpenQ-Contracts/artifacts:/app/artifacts
    entrypoint: [ "yarn", "boot:${DEPLOY_ENV}" ]
  github-oauth-server:
    container_name: github-oauth-server
    build:
      dockerfile: Dockerfile.dev
      context: ./OpenQ-Github-OAuth-Server
    env_file:
      - ./OpenQ-Github-OAuth-Server/.env
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - ./OpenQ-Github-OAuth-Server:/app
  openq-api:
    container_name: openq-api
    build:
      dockerfile: Dockerfile.dev
      context: ./OpenQ-API
    env_file:
      - ./OpenQ-API/.env
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
      - ./OpenQ-API:/app
  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
